# Generated by Django 2.2.4 on 2019-10-19 14:16

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('entrega', models.DateTimeField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Comida')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('cnpj', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('localizacao', models.CharField(max_length=1000)),
                ('descricao_breve', models.CharField(max_length=100, null=True)),
                ('descricao_longa', models.CharField(max_length=500, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=500)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Usuario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Pedido')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos_Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='foto')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos_Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='foto')),
                ('comida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Comida')),
            ],
        ),
        migrations.AddField(
            model_name='comida',
            name='ingredientes',
            field=models.ManyToManyField(to='Delivery.Ingredientes'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Usuario')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao_Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comidas', models.ManyToManyField(to='Delivery.Comida')),
                ('restaurante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
            ],
        ),
    ]
