# Generated by Django 2.2.4 on 2019-10-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Tags')),
            ],
        ),
    ]
